name 'webserver'
maintainer 'Nico Smuts'
maintainer_email 'nico@smuts.me'
license 'MIT License'
description 'Default OpsWorks cookbook.'
long_description 'This is my default cookbook for AWS OpsWorks.'
version '0.1.0'
